TYPE_PI = 100
TYPE_CLIENT = 101

TEMP_SENSOR = 102

SOURCE_ATTR = 'source'
SENSOR_ATTR = 'sensor'
VALUE_ATTR = 'value'
TIME_ATTR = 'time'
MESSAGE_ATTR = 'message'

MQTT_SUBSCRIBER_IP_ADDRESS = '192.168.0.105'
MQTT_SUBSCRIBER_PORT = '1883'
